version: 2.1

workflows:
  catkin-make:
    jobs:
      - catkin-make-test

jobs:
  catkin-make-test:  
    docker:
      - image: kuolunwang/dlp:project
    steps:
      - checkout
      - run:
          name: cake make
          command:
            source /opt/ros/melodic/setup.bash 
            ./catkin_make.sh
